[package]
name = "lattice_generator_app"
version = "0.1.0"
edition = "2024"

[dependencies]
lattice_code_generator = { path = "../lattice_code_generator" }
quote = "1.0" # Needed for TokenStream::to_string()
proc-macro2 = "1.0" # Needed for TokenStream::to_string()
